### ISSUE TITLE
Specific version of go-trees is not targeted in glide.yaml

### ISSUE THREAD

**Issue by ZachEddy** [infobloxopen/themis#167]
# Target Specific Version of go-trees

I'm working on [an application](https://github.com/infobloxopen/atlas-contacts-app/issues) that vendors the PEP, PDP, and PDP Service packages. When I rebuild my vendor tree, I now get the following errors (just started happening yesterday).

```sh
infobloxopen/themis/pdp/attribute.go:159:24: undefined: domaintree.WireDomainNameLower
infobloxopen/themis/pdp/attribute.go:248:13: undefined: domaintree.MakeWireDomainNameLower
infobloxopen/themis/pdp/attribute.go:289:41: undefined: domaintree.WireDomainNameLower
infobloxopen/themis/pdp/attribute.go:405:35: undefined: domaintree.WireDomainNameLower
infobloxopen/themis/pdp/attribute.go:411:14: undefined: domaintree.WireDomainNameLower
infobloxopen/themis/pdp/attribute.go:481:15: undefined: domaintree.WireDomainNameLower
infobloxopen/themis/pdp/content.go:1001:35: undefined: domaintree.WireDomainNameLower
infobloxopen/themis/pdp/context.go:249:60: undefined: domaintree.WireDomainNameLower
```

These errors seem related to [recent changes](https://github.com/infobloxopen/go-trees/commit/5e11a56432a0acca1ebc7e3611aa5dc13e76c3a3) in the in go-trees repository. Because these changes in go-trees are backward incompatible, I think Themis should target a specific commit of go-trees in the `glide.yaml` file.

```yaml
# glide.yaml
- package: github.com/infobloxopen/go-trees
  version: ba3cf0abf6c4176275bfdabf40f4da38da29becb # <-- target a specific commit
  subpackages:
  - domaintree
  - strtree
  - iptree
```
By adding this to the `glide.yaml` file, my dependency management tool will recognize that it needs to pull an older version of go-trees that won't break Themis.

Thanks!
